blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/golangci/golangci-lint-action/discussions
    about: If you have a question, or are looking for advice, please post on our Discussions forum!
  - name: golangci-lint main repository
    url: https://github.com/golangci/golangci-lint
    about: The main repository of golangci-lint.
  - name: golangci-lint documentation
    url: https://golangci-lint.run
    about: Please take a look to our documentation.
